language: generic
sudo: required
services:
  - docker

env:
  global:
    - BINTRAY_USER=roadrunnr
    - secure: "WtyKzfPZKsXwDSq+PJYpkUC98TF+bT3r5ZJxs23vM9GH9wd0PGU9AXwlsUu+xIOtgy05Gw9SqCeOwoQrxn39IRvj3rzuH7SqAktMXXCutCM5/+hQFpc6yuODpql1cQlB+j0xfDt218vnZRums/qxsn463W0wrktz9rheH3+mQl7/sLvcdmiHxt8B2zYIWRHOPySmyhyOER1+BGUTjvPEkdVQxFAbAME1BFihcRNuEQ4742pQ4LpK6PKZeeJ7AdRZRTK3VcH0qFQ4AbgomrOSQMwzo6H/RyJ7nnVnyz4X7PSVVNnKOauzUP+HJ/Vhhx5TMJ6q90OaKPyP9a5E0KeZKnvxE4aEOdTIsIK/sKn8q9rnz7wrHrhcMSiamsa+TGHtZlkjXEGpLs542vNGPgnkIUaYwctw4PpahM1uJ/SWlcn5MseAlSTCSndeES1uVTzgG4QwqyL/8BWKsVF+rL3L+tC5RiHwhgH7FX7poYwZUfyeN3t+tyVFea+8fcGTMIcIXwT/XGjv3Q0Xm8mvfEfY1eXsu5w8r7zx3CU2Q+6M+hKR8gETXSypuctrK7EHmznmbSlq0Mp8gkYJq3tk7jclR9t7FeQdkVxxW0eGNuohCxYAQKX5E5MqeXDjL5LxBeFMRowxHUx9Z78sR38TA3tKrLq0CePsJIPPTAC6Q48TEeE="

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y devscripts
  - docker build -t ergw -f priv/Dockerfile priv

script:
  - export SHORT_COMMIT_ID=$(git rev-parse --verify --short $TRAVIS_COMMIT)
  - debchange -m -l "+$TRAVIS_JOB_NUMBER+git$SHORT_COMMIT_ID" 'Automatically built'
  - mkdir artifacts
  - docker run -v `pwd`:/build ergw
    sh -c "
      dpkg-buildpackage -b -uc && cp ../*deb artifacts
    "

after_success:
  - priv/upload_bintray.sh
  - echo "Done"

notifications:
  slack:
  - secure: "bwk2/vd/EcAEzb9p31G+eI6VscKTlpX5glh2oL31M/5QmWgjPpa1tHwLck11HjNHBdKcnQ2Po9axTn09gMnUGP9XpnYgvmCdx10Qnry4S1O0i2DDICW8txXQY7POUoFGAlbfIVLevsx4Z4RJn1lqivRfQ+t6eHVa8uYobjpwrymg9Xgtq7+nIk08zXZn6OIRPJZT+YdmJKA74SGk/l6FAoqhVNjDVd6IgmAuYTUeqwQfl3Y4dxPCgqeJTovyb0z79dHSGmqSQxqw9sMAE7U+fq8b2c8BvUOb5dJp/Kd2HyNLgKSnt0KtcvKKnRhwYCLorctc9hoYnl9dvfwqm1UgR9mdWDDbu470j4xj5s8HWr1+zCqw2eSooBLPRbE8Qoe9I2OZ3NhryduGNIsRLW1A32TCemsRXZG6h96Sun/YZuEREKCzNR8Kdj35m6Mxj/aBbSE7ALWK3QjHq5Z4SV/UMRGtCRlm/WK+AO10cxSH7E1siud++5ZwtIogFQPZB40uJOlKnIDmyirk8jX2Vojkcy5/xG+HFeUQkXmM1JtAEIhrGOS2hZcs79jqGGEXoCOJ0MSxtdlkh03Z+eu7gJmAel0lrZ9sEv2NxXqDexti+HxYdpDzu4Gwy8d4NjhYMaITjsJyy6v1gQfy8W3bJkCzvb1GpebY3iWS72HUXXrMJ9g="

branches:
  only:
    - master